
services:
  worker:
    image: node:18
    working_dir: /app
    init: true
    command: yarn start
    restart: always
    environment:
      PORT: 28282
      HTTP_PORT: 28280
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 127.0.0.1:28282:28282
      - 127.0.0.1:28280:28280
volumes:
  node_modules:
