
services:
  worker:
    image: node:18
    working_dir: /app
    init: true
    command: yarn start
    restart: always
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 127.0.0.1:22225:22222
volumes:
  node_modules:
